### ISSUE TITLE
Activity opens to a white screen.

### ISSUE THREAD

**Issue by chimosky** [marsian83/latin-squares-activity#1]
Activity opens to a white canvas;

![Screenshot from 2024-07-28 17-15-00](https://github.com/user-attachments/assets/c33b98a2-5121-422a-a2ef-30bde03928e3)

Help button has no effect, and this is in the logs;
```python3
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Traceback (most recent call last):
  File "/home/ibiam/Activities/latin-squares-activity/main.py", line 72, in run
    self.set_screen(game.view)
  File "/home/ibiam/Activities/latin-squares-activity/main.py", line 52, in set_screen
    view(self)
  File "/home/ibiam/Activities/latin-squares-activity/views/game.py", line 40, in view
    next_level()
  File "/home/ibiam/Activities/latin-squares-activity/views/game.py", line 34, in next_level
    level += 1
    ^^^^^
UnboundLocalError: cannot access local variable 'level' where it is not associated with a value
Traceback (most recent call last):
  File "/home/ibiam/Activities/latin-squares-activity/activity.py", line 82, in show_help
    self.game.show_help()
  File "/home/ibiam/Activities/latin-squares-activity/main.py", line 58, in show_help
    self.help_popup.show()
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'show'
Traceback (most recent call last):
  File "/home/ibiam/Activities/latin-squares-activity/activity.py", line 82, in show_help
    self.game.show_help()
  File "/home/ibiam/Activities/latin-squares-activity/main.py", line 58, in show_help
    self.help_popup.show()
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'show'
```

**Comment by marsian83** [comment]
I have fixed this bit
But I already had, I had a little disaster
I use VirtualBox for running the VM and SSh into it using VScode server
My Machine had been corrupted and I had not pushed my changes to github, I did not realize that until now, I started the activity and I have lost some progress
Help, Level Counter and Timer are not here
I have fixed the white screen issue and wil be adding back these things soon

**Comment by chimosky** [comment]
That really sucks, everything good with your device now?

I'll wait for your other changes, it'll be great to have the tiles moved a bit lower so they're not that close
to the toolbar.
![Screenshot from 2024-08-28 19-05-24](https://github.com/user-attachments/assets/5ba52ec0-6d4f-471c-b67f-5e73b1b75718)

**Comment by marsian83** [comment]
Fixed padding, added timer, added level display and added help

**Comment by chimosky** [comment]
Tested, help screen overflows.
![Screenshot from 2024-09-04 15-58-11](https://github.com/user-attachments/assets/afd3a9fc-6777-4ba2-8905-2b930b90925b)

**Comment by marsian83** [comment]
I fixed the help overflow, the image now adjusts itself accoridng to screen aspect ratio

**Comment by chimosky** [comment]
Haven't tested yet, could you also fix the icon to maintain sugar's design?

**Comment by marsian83** [comment]
> Haven't tested yet, could you also fix the icon to maintain sugar's design?

updating icon now, did you get around to testing this?

**Comment by chimosky** [comment]
> > Haven't tested yet, could you also fix the icon to maintain sugar's design?
> 
> updating icon now, did you get around to testing this?

I did, and opened #3.

**Comment by chimosky** [comment]
Tested ebf02cd, the screen overflow is fixed but it seems the help button can only be clicked once and the logs show this;
```
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
```

**Comment by marsian83** [comment]
Fixed now

**Comment by marsian83** [comment]
I changed the icon with inkscape. How does it adapt sugar colors now?

**Comment by marsian83** [comment]
I managed to adapt sugar colors, the icon looks better now 😃
are there any changes required or can we publish t he activity?

**Comment by chimosky** [comment]
I'll test your changes, after that we'll publish the activity.

**Comment by marsian83** [comment]
have you gottern around to testing it?

**Comment by marsian83** [comment]
@chimosky Did you test it?

**Comment by chimosky** [comment]
Tested, the activity icon is filled like it should be when it's been opened, but the fill color isn't the user color like it should be.

The help button also only works just once, and refuses to display the help on subsequent clicks, nothing is shown in the logs.

**Comment by marsian83** [comment]
I have fixed the help screen, changed the icon as well

**Comment by chimosky** [comment]
PRs exists so we can agree on your changes before they're merged, you seem not to be making good use of them.

When you make a change, as you're not the only one testing and reviewing this, open a PR so I'll test and point out any issues there and then we'll agree before merging.

Pushing changes when they've not been agreed on just makes it a bit more difficult.

I've not tested, but looking at 4480287, you've also changed the icon name, why is that?

**Comment by marsian83** [comment]
Sorry, will open PRs for changes from now on.

There is no particular reason for the icon name change though

**Comment by chimosky** [comment]
If there's no reason for the icon change, then we can revert back to what it was.
